# Generated by Django 4.1.7 on 2023-04-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_actor_movies_actor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
    ]
