# Generated by Django 4.1.7 on 2023-05-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_remove_actor_movies_director_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.ImageField(default=None, upload_to='directors/'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='режисер', to='films.director'),
        ),
    ]
