# Generated by Django 4.1.7 on 2023-05-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_review_rating_review_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
