# Generated by Django 4.1.7 on 2023-05-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_rename_parent_review_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
