# Generated by Django 4.1.7 on 2023-05-06 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_alter_review_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актор', 'verbose_name_plural': 'Актори'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режисер', 'verbose_name_plural': 'Режисери'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанри'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Обране', 'verbose_name_plural': 'Обране'},
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 26, 34, 129469)),
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
