# Generated by Django 4.1.7 on 2023-05-06 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_remove_movie_genre_alter_review_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 50, 47, 76759)),
        ),
    ]
