# Generated by Django 4.1.7 on 2023-05-08 12:53

import datetime
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_movie_trailer_alter_review_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 15, 53, 41, 476762)),
        ),
    ]
