# Generated by Django 4.1.7 on 2023-05-09 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_alter_movie_trailer_alter_review_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 19, 47, 19, 927421)),
        ),
    ]
