# Generated by Django 4.1.7 on 2023-05-09 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_alter_review_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='url',
            field=models.SlugField(default=0, max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 19, 52, 20, 757392)),
        ),
    ]
